[feat] : 캐릭터 선택시 상세 정보 조회 API 구현 및 swagger 작성
Team-Offroad/Offroad-server pull request #176
Opened 2024-08-13 18:31 UTC by sansan20535

## 변경사항

### 캐릭터 선택시 상세 정보 API

* 캐릭터를 선택하면 보여지는 정보를 응답하는 API를 작성했습니다.

### 누락된 swagger작성

* 누락된 swagger를 작성했습니다.

## Test
<img width="700" alt="image" src="https://github.com/user-attachments/assets/717c9126-aa0b-43f9-898c-702c067a1727">

<img width="264" alt="image" src="https://github.com/user-attachments/assets/9ab9dc9c-d1d3-4506-9507-7071611e8a2b">

2024-08-14 04:51 UTC, jun3327 requested changes
고생하셨습니다! 리뷰 남겼습니다~

2024-08-14 04:51 UTC, jun3327 commented on offroad-api/src/main/java/site/offload/api/character/dto/response/CharacterDetailResponse.java
> +    }
p2;

빌더로 객체 생성해도 좋을 것 같습니다!

2024-08-14 04:51 UTC, jun3327 commented on offroad-api/src/main/java/site/offload/api/character/dto/response/CharacterDetailResponse.java
> +        String CharacterSubColorCode
p1;

characterSubColorCode에 첫글자가 대문자 C로 되어있는데 오타 확인 부탁드립니다!
그리고 characterMainColorCode와 characterSubColorCode가 뷰에서 각각 어떤 것인지 설명해주실 수 있나요?

2024-08-15 07:29 UTC, sansan20535 commented on offroad-api/src/main/java/site/offload/api/character/dto/response/CharacterDetailResponse.java
> +    }
확인해서 수정하겠습니다!

2024-08-15 07:30 UTC, sansan20535 commented on offroad-api/src/main/java/site/offload/api/character/dto/response/CharacterDetailResponse.java
> +        String CharacterSubColorCode
감사합니다! 확인했습니다!! ColorCode는 캐릭터 목록 및 캐릭터 모션 목록에서 보여지는 색상코드를 의미합니다!

2024-08-15 07:41 UTC, jun3327 commented
수정사항 확인했습니다~ 머지할게요~

2024-08-15 07:41 UTC, merged