feat: 공지사항 알림 기능
Team-Offroad/Offroad-server pull request #243
Opened 2024-11-07 08:10 UTC by jun3327

## 변경사항
- fcm과 aws sqs를 이용해서 공지사항 알림 기능을 추가했습니다.
## 고려사항
- 제가 구상한건 대략 아래와 같은 과정을 통해 푸시 알림이 전송됩니다.
<img width="455" alt="image" src="https://github.com/user-attachments/assets/af8212c1-96f7-4a7b-9306-e8a6fdcba196">

- 위 그림에서
  - **1번, 2번**: 공지 db에 일정 시간마다 새로운 공지사항이 있는지 확인합니다. 확인 주기는 사용자에게 알림이 발송되어야 하는 시간보다 작게 설정합니다. https://github.com/Team-Offroad/Offroad-server/blob/02194483439dec1063abf000221c40c8c40eeb1a/offroad-batch/src/main/java/site/offload/batch/announcement/MessageService.java#L50-L54
  - **3번**: 새 공지사항이 있다면, AWS SQS 큐에 공지사항을 식별할 수 있는 메시지를 스케줄링 합니다. Spring Cloud의 SqsTemplate을 사용했습니다 (콘솔에서 대기열 하나 만들어놨습니다). https://github.com/Team-Offroad/Offroad-server/blob/02194483439dec1063abf000221c40c8c40eeb1a/offroad-external/src/main/java/site/offload/external/aws/SqsService.java#L9-L17
  - **4번, 5번**: 우리 서버에서 주기적으로 SQS에 대기중인 메시지가 있는지 확인합니다. Spring Cloud의 @SqsListener 어노테이션을 사용했습니다. 이런식으로 해야하는 이유가, SQS는 대기열의 역할만 하기 때문에 저희 서버에서 확인하는 방법 밖에 없다고 합니다. SQS와 AWS Lamda를 활용하면 서버리스 방식으로 lamda에서 fcm 발송이 가능하다고 하는데, 이 부분은 기한 내 구현이 어려울 것 같아 패스했습니다. https://github.com/Team-Offroad/Offroad-server/blob/02194483439dec1063abf000221c40c8c40eeb1a/offroad-batch/src/main/java/site/offload/batch/announcement/AnnouncementListener.java#L12-L25
  - **6번**: 대기중인 메시지를 확인한 후, FCM 스펙에 맞게 전송할 내용을 구성한 후에 전송 요청을 보냅니다. 주의해야할 점은 FCM이 한 번에 500명한테 발송이 가능하다해서, 각 사용자를 식별하는 registrationToken(클라에서 주고 db에 저장해놔야됨)을 500개씩 잘라서 요청하도록 페이지네이션을 했습니다. https://github.com/Team-Offroad/Offroad-server/blob/02194483439dec1063abf000221c40c8c40eeb1a/offroad-batch/src/main/java/site/offload/batch/announcement/MessageService.java#L110-L116
  - **7번**: FCM에서 각 registrationToken에 해당하는 디바이스로 푸시알림을 전송합니다.
## Comment
- fcm에서 제대로 전송되는지는 클라분들하고 테스트해봐야 될 것 같습니다\
## Test

## 질문사항

2024-11-08 03:51 UTC, sansan20535 requested changes
정말 고생하셨습니다..!! 리뷰 남겼습니다 : )

2024-11-08 03:51 UTC, sansan20535 commented on offroad-api/src/main/resources/application-local.yaml
> +        announcement-url: ${AWS_SQS_ANNOUNCEMENT_QUEUE_URL}
p1

해당 내용이 secrets이외에도 프로젝트 내의 application-dev.yml에도 필요할 것 같습니다..! (지난 번 애플 소셜 로그인 때 추가를 안하니 환경변수를 인식 못했던 것 같습니다!)

2024-11-08 03:51 UTC, sansan20535 commented on offroad-db/src/main/java/site/offload/db/setting/entity/SettingEntity.java
> +public class SettingEntity {
p4 

혹시 이 엔티티의 역할을 무엇인지 여쭤봐도 되나요??

2024-11-08 04:12 UTC, jun3327 commented on offroad-api/src/main/resources/application-local.yaml
> +        announcement-url: ${AWS_SQS_ANNOUNCEMENT_QUEUE_URL}
넵! 이 부분 추가하겠습니다

2024-11-08 04:14 UTC, jun3327 commented on offroad-db/src/main/java/site/offload/db/setting/entity/SettingEntity.java
> +public class SettingEntity {
앱이 중단되거나 갑자기 다운 됐을 때 Setting에 공지사항이 어느 id까지 전송 됐는지 저장해놓고 알림 서비스 실행 시 Setting 엔티티에서 그 값을 가져오게 됩니다! 별도로 저장해놓는게 좋을 것 같아서 db에 저장시켰습니다

2024-11-09 04:13 UTC, unanchoi approved these changes
확인..!

2024-11-10 10:50 UTC, merged