refactor: 채팅 커서기반 페이지네이션 적용
Team-Offroad/Offroad-server pull request #269
Opened 2024-11-28 16:48 UTC by unanchoi

## 변경사항
- 채팅의 cursor (id 기준) 기반으로 페이지네이션을 적용했습니다.

## 고려사항

## Comment

## Test

## 질문사항

2024-11-29 01:39 UTC, jun3327 requested changes
확인했습니다! 리뷰남겼습니다

2024-11-29 01:39 UTC, jun3327 commented on offroad-api/src/main/java/site/offload/api/chatting/usecase/ChatUseCase.java
> +            return chatService.findAll(memberId, character.getId(), limit, cursor)
p4;

혹시 characterId가 null일 때가 어떤 상황이었는지 다시 한 번만 설명해주실 수 있나요? 저번 회의 때 설명해주신 것 같은데 제가 헷갈려서 다시 한 번만 부탁드립니다..

2024-11-29 01:39 UTC, jun3327 commented on offroad-db/src/main/java/site/offload/db/chat/repository/ChatRepository.java
> +    ORDER BY c.id DESC
p1;

원래는 생성 순서 오름차순으로 반환되고 있었는데 order by가 desc가 아닌 asc가 되어야하는 것이 아닌지 여쭙니다!
그리고 cursor가 클라에서 오는 서버가 전송한 로그 리스트 중 마지막 객체의 id값이라면 where문의 부등호가 반대로 되어야 하지 않을까요??

2024-11-29 01:39 UTC, jun3327 commented on offroad-api/src/main/java/site/offload/api/chatting/service/ChatService.java
> +        return chatRepository.findChatLogsByMemberEntityIdAndCharacterIdByCursor(memberId, characterId, null, pageable);
p2;

여기 세 번째 인자에 null이 들어가 있는데 cursorId가 들어가야 하는 부분이 아닌지 여쭙니다!

2024-11-29 02:02 UTC, unanchoi commented on offroad-db/src/main/java/site/offload/db/chat/repository/ChatRepository.java
> +    ORDER BY c.id DESC
채팅이다보니까, 최신 -> 이전 으로 가야하고
채팅이 Auto Increment로 쌓이니 큰 -> 작은 순으로 정렬 되어야 한다고 생각해서 DESC로 정렬했습니다 ~
그래서 cursor도 마지막 가장 작은 index보다 작은 id를 불러오도록 구현했어요.

2024-11-29 02:02 UTC, unanchoi commented on offroad-api/src/main/java/site/offload/api/chatting/service/ChatService.java
> +        return chatRepository.findChatLogsByMemberEntityIdAndCharacterIdByCursor(memberId, characterId, null, pageable);
헉 그러네요 .. 실수!

2024-11-29 02:03 UTC, unanchoi commented on offroad-api/src/main/java/site/offload/api/chatting/usecase/ChatUseCase.java
> +            return chatService.findAll(memberId, character.getId(), limit, cursor)
characterId가 null일때는 현재 유저의 대표 캐릭터로 채팅을 하게 됩니다 ~

2024-11-29 02:27 UTC, jun3327 commented on offroad-db/src/main/java/site/offload/db/chat/repository/ChatRepository.java
> +    ORDER BY c.id DESC
아하 이해했습니다 감사합니다! 근데 페지네이션 적용 전인 이전 로직에선 클라측에서 생성 순서 오름차순 (이전 -> 최신)으로 저희한테 데이터 받아서 ui가 구현되어 있는 것으로 알고 잇는데, 이 부분은 저희가 바꿔서 혼동이 있지는 않을까요??

별개로 이대로 간다면 맨첨 요청 올 때는 저희가 cursor를 임의로 long 최대값으로 바꾸거나 클라에서 최대값을 넣어서 요청하도록 노티해드려야 할 것 같네요!

2024-12-01 14:52 UTC, jun3327 approved these changes
수정사항 확인했습니다! 머지할게요

2024-12-01 14:53 UTC, merged