Refactor: 장소 조회 API 리팩토링.
Team-Offroad/Offroad-server pull request #281
Opened 2024-12-03 19:06 UTC by unanchoi

## 변경사항
- 기존 장소 조회 API가 장소 목록 조회 상황 2개를 커버하고 있었는데, 정렬 방식의 차이로 인해 핸들링 하기 어려워져 2개의 API로 분리했습니다.
- places/map ->  목록 조회(지도 내에서 조회)
- places/list -> 목록 조회 (커서 기반 페이지네이션)

## 고려사항
- 기존 API가 있어서 임시로, places/list로 목록 조회 API를 만들었으나, 엔드포인트를 나중에 변경할 예정.(places/list -> places/로 변경해야함!)

## Comment

## Test

## 질문사항

2024-12-04 07:30 UTC, junseo511 commented
서버친구들 리뷰할때까지 숨 참습니다 😖

2024-12-04 08:21 UTC, jun3327 requested changes
확인했습니다! 리뷰 남겼습니다

2024-12-04 08:21 UTC, jun3327 commented on offroad-api/src/main/java/site/offload/api/place/usecase/PlaceUseCase.java
> +                placeService.findTopNByCurrentLatitudeAndCurrentLongitude(currentLatitude, currentLongitude, limit)
p1;

여기 네 번째 인자에 null이 들어가야 될 것 같습니다!

2024-12-04 16:12 UTC, unanchoi commented on offroad-api/src/main/java/site/offload/api/place/usecase/PlaceUseCase.java
> +                placeService.findTopNByCurrentLatitudeAndCurrentLongitude(currentLatitude, currentLongitude, limit)
지도에서 조회할때는 cursor가 필요없을 것 같아서 제외했습니다 ~!

2024-12-05 00:53 UTC, jun3327 commented on offroad-api/src/main/java/site/offload/api/place/usecase/PlaceUseCase.java
> +                placeService.findTopNByCurrentLatitudeAndCurrentLongitude(currentLatitude, currentLongitude, limit)
앗.. findTopNByCurrentLatitudeAndCurrentLongitude()가 오버로딩돼있는걸 지금 봤네요! 확인했습니다

2024-12-10 15:40 UTC, unanchoi commented
장소 조회시에 cursor로 거리가 필요하여, 추가로 커밋했습니다 ~

2024-12-11 14:02 UTC, jun3327 approved these changes
거리 반환까지 확인했습니다! 고생하셨습니다

2024-12-11 14:03 UTC, merged