[feat] : Apple Social Login 구현
Team-Offroad/Offroad-server pull request #56
Opened 2024-07-11 20:07 UTC by sansan20535

## 변경사항

https://github.com/Team-Offroad/Offroad-server/blob/1c2cf303a96fa8bb28d2914090fee9009c0fae0a/src/main/java/site/offload/offloadserver/external/oauth/apple/AppleSocialLoginService.java#L31-L46

* claim에서 name, email, sub를 가져와 member를 build하였습니다.

https://github.com/Team-Offroad/Offroad-server/blob/1c2cf303a96fa8bb28d2914090fee9009c0fae0a/src/main/java/site/offload/offloadserver/external/oauth/apple/AppleIdentityTokenParser.java#L20-L45

* 인증코드를 이용하여 Map<String, String>으로 파싱합니다.
* 인증코드와 publicKey로 이용하여 정보가 담긴 claim을 생성합니다.

https://github.com/Team-Offroad/Offroad-server/blob/1c2cf303a96fa8bb28d2914090fee9009c0fae0a/src/main/java/site/offload/offloadserver/external/oauth/apple/ApplePublicKeysResponse.java#L8-L16

https://github.com/Team-Offroad/Offroad-server/blob/1c2cf303a96fa8bb28d2914090fee9009c0fae0a/src/main/java/site/offload/offloadserver/external/oauth/apple/ApplePublicKeyGenerator.java#L23-L43

* 인증코드를 이용해 여러개의 public 키들을 가져온 뒤 일치하는 publickey를 찾습니다.

## Comment

https://github.com/Team-Offroad/Offroad-server/blob/1c2cf303a96fa8bb28d2914090fee9009c0fae0a/src/main/java/site/offload/offloadserver/api/member/controller/SocialLoginController.java#L29

* 이후 리팩토링 과정을 통해 try-catch를 이용하여 커스텀 에러를 발생할 예정입니다.

https://github.com/Team-Offroad/Offroad-server/blob/1c2cf303a96fa8bb28d2914090fee9009c0fae0a/src/main/java/site/offload/offloadserver/external/oauth/apple/AppleIdentityTokenParser.java#L36

* ErrorMessage는 각 상황에 맞게 리팩토링 할 예정입니다.

## 질문사항

https://github.com/Team-Offroad/Offroad-server/blob/1c2cf303a96fa8bb28d2914090fee9009c0fae0a/src/main/java/site/offload/offloadserver/external/oauth/apple/AppleIdentityTokenValidator.java#L18-L19
* clientId를 teamId가 아닌 개인 keyId로 했는데 맞는지가 궁금합니다.

2024-07-11 20:22 UTC, jun3327 requested changes
구현하시느라 고생하셨습니다! 사용자 정보를 반환하는게 여러 단계인 만큼 테스트 후 수정할 점은 수정하면 좋을 것 같습니다!

2024-07-11 20:22 UTC, jun3327 commented on src/main/java/site/offload/offloadserver/external/oauth/apple/ApplePublicKeyGenerator.java
> +            throw new UnAuthorizedException(ErrorMessage.JWT_UNAUTHORIZED_EXCEPTION);
p2;

예외 메세지는 소셜로그인 예외에 맞게 바꿔주시면 좋을 것 같습니다!

2024-07-12 03:36 UTC, sansan20535 commented on src/main/java/site/offload/offloadserver/external/oauth/apple/ApplePublicKeyGenerator.java
> +            throw new UnAuthorizedException(ErrorMessage.JWT_UNAUTHORIZED_EXCEPTION);
넵 이후 테스트에 맞게 세세하게 수정하겠습니다! 감사합니다 : )

2024-07-12 03:36 UTC, unanchoi approved these changes
문제 없어 보입니다 ~

2024-07-12 03:53 UTC, jun3327 commented on src/main/java/site/offload/offloadserver/external/oauth/apple/ApplePublicKeyGenerator.java
> +            throw new UnAuthorizedException(ErrorMessage.JWT_UNAUTHORIZED_EXCEPTION);
넵 머지하겠습니다

2024-07-12 03:53 UTC, merged